$(arg prefix2)ur5_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - $(arg prefix2)shoulder_pan_joint
    - $(arg prefix2)shoulder_lift_joint
    - $(arg prefix2)elbow_joint
    - $(arg prefix2)wrist_1_joint
    - $(arg prefix2)wrist_2_joint
    - $(arg prefix2)wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    $(arg prefix2)shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    $(arg prefix2)shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    $(arg prefix2)elbow_joint: {trajectory: 0.1, goal: 0.1}
    $(arg prefix2)wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    $(arg prefix2)wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    $(arg prefix2)wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  gains:
    $(arg prefix2)shoulder_pan_joint:
      p: 1000
      d: 50
      i: 10
      i_clamp: 100
    $(arg prefix2)shoulder_lift_joint:
      p: 5000
      d: 30
      i: 100
      i_clamp: 400
    $(arg prefix2)elbow_joint:
      p: 5000
      d: 50
      i: 10
      i_clamp: 100
    $(arg prefix2)wrist_1_joint:
      p: 200
      d: 20
      i: 10
      i_clamp: 100
    $(arg prefix2)wrist_2_joint:
      p: 100
      d: 10
      i: 0.1
      i_clamp: 100
    $(arg prefix2)wrist_3_joint:
      p: 10
      d: 1
      i: 0.1
      i_clamp: 100
$(arg prefix2)gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - $(arg prefix2)robotiq_85_left_knuckle_joint
  gains:
    $(arg prefix2)robotiq_85_left_knuckle_joint:
      p: 40
      d: 0
      i: 0
      i_clamp: 1
