ur5_arm1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm1_shoulder_pan_joint
    - arm1_shoulder_lift_joint
    - arm1_elbow_joint
    - arm1_wrist_1_joint
    - arm1_wrist_2_joint
    - arm1_wrist_3_joint
  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0.05
    arm1_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    arm1_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    arm1_elbow_joint: {trajectory: 0.1, goal: 0.1}
    arm1_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    arm1_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    arm1_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  gains:
    arm1_shoulder_pan_joint:
      p: 1000
      d: 50
      i: 10
      i_clamp: 100
    arm1_shoulder_lift_joint:
      p: 5000
      d: 30
      i: 100
      i_clamp: 400
    arm1_elbow_joint:
      p: 5000
      d: 50
      i: 10
      i_clamp: 100
    arm1_wrist_1_joint:
      p: 200
      d: 20
      i: 10
      i_clamp: 100
    arm1_wrist_2_joint:
      p: 100
      d: 1
      i: 0.1
      i_clamp: 100
    arm1_wrist_3_joint:
      p: 10
      d: 0.1
      i: 0.1
      i_clamp: 100
ur5_arm2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm2_shoulder_pan_joint
    - arm2_shoulder_lift_joint
    - arm2_elbow_joint
    - arm2_wrist_1_joint
    - arm2_wrist_2_joint
    - arm2_wrist_3_joint
  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0.05
    arm2_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    arm2_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    arm2_elbow_joint: {trajectory: 0.1, goal: 0.1}
    arm2_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    arm2_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    arm2_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  gains:
    arm2_shoulder_pan_joint:
      p: 1000
      d: 50
      i: 10
      i_clamp: 100
    arm2_shoulder_lift_joint:
      p: 5000
      d: 30
      i: 100
      i_clamp: 400
    arm2_elbow_joint:
      p: 5000
      d: 50
      i: 10
      i_clamp: 100
    arm2_wrist_1_joint:
      p: 200
      d: 1
      i: 0.1
      i_clamp: 100
    arm2_wrist_2_joint:
      p: 100
      d: 1
      i: 0.1
      i_clamp: 100
    arm2_wrist_3_joint:
      p: 100
      d: 0.1
      i: 0.1
      i_clamp: 100
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm2_robotiq_85_left_knuckle_joint
  gains:
    arm2_robotiq_85_left_knuckle_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
